name: Employe Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Unit-Testing
        run: ./gradlew testDebugUnitTest
      - name: test-report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}